### ISSUE TITLE
Security issue - Pagekit's request password feature allows user acc enumeration

### ISSUE THREAD

**Issue by mirkobrombin** [mirkobrombin/pagekit#10]
Ref: https://github.com/pagekit/pagekit/issues/935
File: app/system/modules/user/src/Controller/ResetPasswordController.php:30

**Comment by tobbexiv** [comment]
I checked this fix after the discussion in the original issue and I would say that the issue is still not solved completely:
* If an account is blocked, the enumeration would still be possible as a different message is shown.
* If sending of the email fails, also an error message would be displayed.

My suggestion would be to reduce the coding even more so that the system response will be the same if an email is entered. If errors occur, the messages should only be displayed in debug mode (if we want to display them) and otherwise just logged.

**Comment by mirkobrombin** [comment]
This is a temporary solution. Much of the code under the original PageKit is (sadly) questionable. Your solution could be the definitive way to solve the problem.

At the moment I am busy with the update to uikit3 which is giving me several problems and I don't have the time to devote to this fix.

**Comment by tobbexiv** [comment]
No worries :) I just wanted to write this down somewhere to not forget it (and maybe re-open the issue).

If you need help in the JS part of the upgrade, give me a heads up / note it in the corresponding issue and I will try to find some time to help.

**Comment by mirkobrombin** [comment]
> No worries :) I just wanted to write this down somewhere to not forget it (and maybe re-open the issue).
> 
> If you need help in the JS part of the upgrade, give me a heads up / note it in the corresponding issue and I will try to find some time to help.

I will come back to the problem in the next few days . I will publish the problems I am experiencing in the issue, thanks
